### ISSUE TITLE
Request Response Delay Feature not supported

### ISSUE THREAD

**Issue by tjpsantiago16** [COVESA/vsomeip#268] opened 2021-07-16 06:19 UTC
Hi @lutzbichler ,

Is the request response delay feature supported by vsomeip 3.1.20.3?

There is an element for configuring the request response delay in the json configuration however the configured value is never used.

I also noticed that when configuring request response delay, a single value is required by the json configuration file. However, the [AUTOSAR_PRS_SOMEIPServiceDiscoveryProtocol_1.5.1](https://www.autosar.org/fileadmin/user_upload/standards/foundation/19-11/AUTOSAR_PRS_SOMEIPServiceDiscoveryProtocol.pdf) states that it should be configured with a minimum and maximum value.

**[PRS_SOMEIPSD_00420]** REQUEST_RESPONSE_DELAY shall be specified by a minimum and a maximum. (RS_SOMEIPSD_00025)

**Comment by goncaloalmeida** [comment] 2023-09-08 15:35
Duplicate of https://github.com/COVESA/vsomeip/issues/268

**Closed by goncaloalmeida** 2023-09-08 15:35 UTC
