### ISSUE TITLE
Configuration option deserialize bug.

### ISSUE THREAD

**Issue by yunfeiyangcc** [COVESA/vsomeip#263] opened 2021-07-07 09:50 UTC
@lutzbichler 

Hi lutzbichler,

There are two IPv4 option and a configuration option in the subscribe message.
Order as follows:
0: Configuration Option
1: IPv4 Endpoint Option (192.168.116.131:41234(TCP))
2: IPv4 Endpoint Option (192.168.116.131:44234(UDP))
![image](https://user-images.githubusercontent.com/8465050/124738297-5cf47d00-df4b-11eb-8001-b40bd3f3df74.png)

When the SD receives this subscribe message and deserialize it.
Because the remaining_length is set by options_length_(45), the length of configuration option is 18. 
**so it cannot stop deserializing until the end of the subscribe message.**

I made a change in function(configuration_option_impl::deserialize), please check it.
![image](https://user-images.githubusercontent.com/8465050/124738677-c1174100-df4b-11eb-8828-83d7e53d91d9.png)

**Comment by lutzbichler** [comment] 2021-07-10 14:24
I am afraid I do need to see the message bytes to understand the root cause.

**Comment by ims0** [comment] 2021-12-08 06:54
I also encountered this problem. The solution is to exit if the length is equal to 0.
![image](https://user-images.githubusercontent.com/32973352/145162290-5dcca85d-bcbc-48a5-9a99-7e96b8194b94.png)

**Comment by DiogoPedrozza** [comment] 2023-06-05 14:25
Hi all.
Fix also introduced in [3.3.5.1](https://github.com/COVESA/vsomeip/releases/tag/3.3.5.1) and present on all the subsequent releases.
Closing the issue.

**Closed by DiogoPedrozza** 2023-06-05 14:25 UTC
